name    'treydock-mock'
version '0.0.1'
source 'git://github.com/treydock/puppet-mock'
author 'treydock'
license 'Apache License, Version 2.0'
summary 'puppet-mock'
description 'puppet-mock'
project_page 'http://github.com/treydock/puppet-mock'
dependency 'puppetlabs/stdlib', '>=3.2.0 <5.0.0'
dependency 'stahnma/epel', '>=0.0.1 <1.0.0'
